// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import { ANTHROPIC_MODELS } from "./providers/anthropic.models.ts";
import { DEEPSEEK_MODELS } from "./providers/deepseek.models.ts";
import { MOONSHOTAI_MODELS } from "./providers/moonshotai.models.ts";
import { OPENAI_MODELS } from "./providers/openai.models.ts";
import { ZAI_MODELS } from "./providers/zai.models.ts";

export const MODELS: {
	readonly "anthropic": typeof ANTHROPIC_MODELS;
	readonly "deepseek": typeof DEEPSEEK_MODELS;
	readonly "moonshotai": typeof MOONSHOTAI_MODELS;
	readonly "openai": typeof OPENAI_MODELS;
	readonly "zai": typeof ZAI_MODELS;
} = {
	"anthropic": ANTHROPIC_MODELS,
	"deepseek": DEEPSEEK_MODELS,
	"moonshotai": MOONSHOTAI_MODELS,
	"openai": OPENAI_MODELS,
	"zai": ZAI_MODELS,
};
