#!/usr/bin/env node

import { mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import {
	createModelDataManifest,
	MODEL_DATA_MANIFEST_FILE,
	type ModelDataStructure,
	validateGeneratedModelData,
} from "./model-data.ts";

const packageRoot = join(import.meta.dirname, "..");
const providersDir = join(packageRoot, "src", "providers");
const dataDir = join(providersDir, "data");
const providerIds = ["anthropic", "deepseek", "moonshotai", "openai", "zai"] as const;

interface Options {
	dataOnly: boolean;
	jsonOnly: boolean;
	jsonOutput?: string;
	pretty: boolean;
}

function parseArgs(args: string[]): Options {
	const options: Options = {
		dataOnly: false,
		jsonOnly: false,
		pretty: false,
	};

	for (let index = 0; index < args.length; index++) {
		const arg = args[index];
		if (arg === "--strict") continue;
		if (arg === "--data-only") {
			options.dataOnly = true;
			continue;
		}
		if (arg === "--json-only") {
			options.jsonOnly = true;
			continue;
		}
		if (arg === "--pretty") {
			options.pretty = true;
			continue;
		}
		if (arg === "--json-output") {
			const value = args[++index];
			if (!value) throw new Error("--json-output requires a directory");
			options.jsonOutput = value;
			continue;
		}
		throw new Error("Unknown argument: " + arg);
	}

	if (options.dataOnly && options.jsonOnly) throw new Error("--data-only and --json-only cannot be combined");
	return options;
}

function readProviderData(providerId: string): Record<string, Record<string, unknown>> {
	const path = join(dataDir, providerId + ".json");
	const value: unknown = JSON.parse(readFileSync(path, "utf8"));
	if (typeof value !== "object" || value === null || Array.isArray(value)) {
		throw new Error(providerId + ".json must contain API groups");
	}
	return value as Record<string, Record<string, unknown>>;
}

function readCatalog(): Record<string, Record<string, Record<string, unknown>>> {
	return Object.fromEntries(providerIds.map((providerId) => [providerId, readProviderData(providerId)]));
}

function flatten(groups: Record<string, Record<string, unknown>>): Record<string, unknown> {
	return Object.assign({}, ...Object.values(groups));
}

function buildStructure(catalog: Record<string, Record<string, Record<string, unknown>>>): ModelDataStructure {
	return Object.fromEntries(
		providerIds.map((providerId) => [
			providerId,
			Object.fromEntries(
				Object.entries(catalog[providerId]).flatMap(([api, models]) =>
					Object.keys(models).map((modelId) => [modelId, api] as const),
				),
			),
		]),
	) as ModelDataStructure;
}

function json(value: unknown, pretty: boolean): string {
	return JSON.stringify(value, null, pretty ? 2 : 0) + "\n";
}

function providerConstant(providerId: string): string {
	return providerId.toUpperCase() + "_MODELS";
}

function modelShard(providerId: string): string {
	return [
		"// This file is auto-generated by scripts/generate-models.ts",
		"// Do not edit manually - run 'npm run generate-models' to update",
		"",
		'import values from "./data/' + providerId + '.json" with { type: "json" };',
		'import { flattenModelCatalog, type ModelCatalog } from "../model-catalog.ts";',
		"",
		"export const " + providerConstant(providerId) + ': ModelCatalog<typeof values, "' + providerId + '"> =',
		'\tflattenModelCatalog("' + providerId + '", values);',
		"",
	].join("\n");
}

function modelAggregator(): string {
	const imports = providerIds.map(
		(providerId) => 'import { ' + providerConstant(providerId) + ' } from "./providers/' + providerId + '.models.ts";',
	);
	const entries = providerIds.map(
		(providerId) => '\t"' + providerId + '": ' + providerConstant(providerId) + ",",
	);
	return [
		"// This file is auto-generated by scripts/generate-models.ts",
		"// Do not edit manually - run 'npm run generate-models' to update",
		"",
		...imports,
		"",
		"export const MODELS: {",
		...providerIds.map((providerId) => '\treadonly "' + providerId + '": typeof ' + providerConstant(providerId) + ";"),
		"} = {",
		...entries,
		"};",
		"",
	].join("\n");
}

function writeModelData(catalog: Record<string, Record<string, Record<string, unknown>>>, pretty: boolean): void {
	mkdirSync(dataDir, { recursive: true });
	for (const providerId of providerIds) {
		writeFileSync(join(dataDir, providerId + ".json"), json(catalog[providerId], pretty));
	}

	const structure = buildStructure(catalog);
	const fileContents = Object.fromEntries(
		providerIds.map((providerId) => [providerId + ".json", readFileSync(join(dataDir, providerId + ".json"), "utf8")]),
	);
	const manifest = createModelDataManifest(structure, fileContents, new Date().toISOString());
	writeFileSync(join(dataDir, MODEL_DATA_MANIFEST_FILE), json(manifest, false));
}

function writeTypeScriptCatalog(): void {
	for (const providerId of providerIds) {
		writeFileSync(join(providersDir, providerId + ".models.ts"), modelShard(providerId));
	}
	writeFileSync(join(packageRoot, "src", "models.generated.ts"), modelAggregator());
}

function writeJsonCatalog(
	catalog: Record<string, Record<string, Record<string, unknown>>>,
	outputPath: string,
	pretty: boolean,
): void {
	const outputDir = resolve(outputPath);
	rmSync(outputDir, { recursive: true, force: true });
	mkdirSync(join(outputDir, "providers"), { recursive: true });
	const models = Object.fromEntries(providerIds.map((providerId) => [providerId, flatten(catalog[providerId])]));
	writeFileSync(join(outputDir, "models.json"), json(models, pretty));
	writeFileSync(join(outputDir, "providers.json"), json([...providerIds].sort(), pretty));
	for (const providerId of providerIds) {
		writeFileSync(join(outputDir, "providers", providerId + ".json"), json(models[providerId], pretty));
	}
}

function main(): void {
	const options = parseArgs(process.argv.slice(2));
	const catalog = readCatalog();
	if (!options.jsonOnly) writeModelData(catalog, options.pretty);
	if (!options.dataOnly && !options.jsonOnly) writeTypeScriptCatalog();
	if (options.jsonOutput) writeJsonCatalog(catalog, options.jsonOutput, options.pretty);
	if (!options.jsonOnly) validateGeneratedModelData(packageRoot);
	if (options.jsonOutput) console.log("Generated model catalog at " + resolve(options.jsonOutput));
	else console.log("Generated model data for " + providerIds.join(", ") + ".");
}

main();
